In [85]:
import random

# StringIO behaves like a file object 
from io import StringIO 

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
from sklearn.datasets import load_boston
from sklearn import linear_model
from sklearn.metrics import r2_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler
import statsmodels.api as sm
import statsmodels.formula.api as smf

import copy

%matplotlib inline

In [86]:
def median(a,b,c):
    if a > b:
        if a < c:
            return a
        elif b > c:
            return b
        else:
            return c
    else:
        if a > c:
            return a
        elif b < c:
            return b
        else:
            return c

In [87]:
class CqkProblem:
    def __init__(self, r, n, d, a, b, low, up):
        self.n = n
        self.r = r
        self.d = list(d)
        self.a = list(a)
        self.b = list(b)
        self.low = list(low)
        self.up = list(up)

In [88]:
def generate_cqk_problem(n):
    d = []
    low = []
    up = []
    b = []
    a = []
    temp = 0
    lb = 0.0
    ub = 0.0
    lower = 10
    upper = 25
    r = 0

    for i in range(n):
        
        b.append(10 + 14*random.random())
        low.append(1 + 14*random.random())
        up.append(1 + 14*random.random())
        if low[i] > up[i]:
            temp = low[i]
            low[i] = up[i]
            up[i] = temp
        
        lb = lb + b[i]*low[i];
        ub = ub + b[i]*up[i];
        
        #Uncorrelated
        d.append(random.randint(10,25))
        a.append(random.randint(10,25))
        
    r = lb + (ub - lb)*0.7;
    
    return CqkProblem( r, n, d, a, b, low, up)

In [89]:

def initial_lambda(p, lamb):
    s0=0.0
    q0=0.0
    slopes = []
    for i in range(p.n):
        slopes.append((p.b[i]/p.d[i])*p.b[i])
        s0 = s0 + (p.a[i] * p.b[i]) / p.d[i]
        q0 = q0 + (p.b[i] * p.b[i]) / p.d[i]
    lamb = (p.r-s0)/q0
    return lamb, slopes

In [90]:
def phi_lambda(p,lamb,phi,deriv,slopes,r):
    deriv = 0.0
    phi = r * -1
    x = []
    
    for i in range(p.n):
        
        x.append( (p.b[i] * lamb + p.a[i])/p.d[i])

        if x[i] < p.low[i]:
            x[i] = p.low[i]
        elif x[i] > p.up[i]:
            x[i] = p.up[i]
        else:
            deriv = deriv + slopes[i];
        phi = phi + p.b[i] * x[i];
    return deriv, phi, x

In [162]:
MAX_IT = 20
INFINITO_NEGATIVO = -999999999;
INFINITO_POSITIVO = 999999999;

def newton(p):
    lambs = [] 
    phi = 0
    lamb = 0
    alfa = INFINITO_NEGATIVO;
    beta = INFINITO_POSITIVO;
    phi_alfa = 0.0;
    phi_beta = 0.0;
    deriv = 0
    x = []
    r = p.r
    
    lamb, slopes = initial_lambda(p,lamb)
    deriv, phi, x = phi_lambda(p,lamb,phi,deriv,slopes,r)
    lambs.append(lamb)
    it = 1
#     print(it, deriv, phi,lamb)
    negativo = False
    while phi != 0.0 and it <= MAX_IT:
        if phi > 0:
#             print("positivo")
            beta = lamb
            lambda_n = 0.0
            if deriv > 0.0:
                
                lambda_n = lamb - (phi/deriv)
                if abs(lambda_n - lamb) <= 0.00000000001:
                    phi = 0.0
                    break
                if lambda_n > alfa:
                    lamb = lambda_n
                else:
#                     print("aqui")
                    phi_beta = phi;
#                     lamb = secant(p,x,alfa,beta,phi_alfa,phi_beta,r);
#             if deriv == 0.0:
#                 lamb = breakpoint_to_the_left(p,lamb);
#                 if lamb <= INFINITO_NEGATIVO or lamb >= INFINITO_POSITIVO:
#                     break
                
        else:
            if it == 1:
                negativo = True
#             print("negativo")
            alfa = lamb;
            lambda_n = 0.0;

            if deriv > 0.0:
                lambda_n = lamb - (phi/deriv)
                if abs(lambda_n - lamb) <= 0.00000000001:
                    phi = 0.0
                    break
                
                if lambda_n < beta:
                    lamb = lambda_n
                else:
#                     print("aqui")
                    phi_alfa = phi;
#                     lamb = secant(p,x,alfa,beta,phi_alfa,phi_beta,r);
#             if deriv == 0.0:
#                 lamb = breakpoint_to_the_right(p,lamb)
#                 if lamb <= INFINITO_NEGATIVO or lamb >= INFINITO_POSITIVO:
#                     break
        
        
        deriv, phi, x = phi_lambda(p,lamb,phi,deriv,slopes,r)
        it = it + 1
        lambs.append(lamb)
        
    if phi == 0.0:
        return it,lambs, negativo
    elif alfa == beta:
        return -1,lambs, negativo
    else:
        return -2,lambs, negativo

In [163]:
def func_ty(p):
    t = np.arange(0, 15, 0.5).tolist()
    y = copy.deepcopy(t)
    for j in range(len(t)):
        lamb = t[j]

        soma = 0

        for i in range(n):
            soma = soma + p.b[i] * median(p.low[i], (p.b[i] *lamb + p.a[i]) / p.d[i], p.up[i])

        y[j] = soma
    return y

In [206]:
lista = []
for i in range(10000):
    n = 3
    p = generate_cqk_problem(n)
    it,lambs, negativo = newton(p)
#     soma_a = 0
#     soma_b = 0
#     soma_low = 0
#     soma_d = 0
#     soma_up = 0
#     for i in range(n):
#         soma_a += p.a[i]
#         soma_b += p.b[i]
#         soma_low += p.low[i]
#         soma_d += p.d[i]
#         soma_up += p.up[i]
    
#     soma_a = soma_a/n
#     soma_b = soma_b/n
#     soma_low = soma_low/n
#     soma_d = soma_d/n
#     soma_up = soma_up/n
    
#     l_rs = [soma_a, soma_b, soma_low, soma_up, soma_d, p.r, lambs[0], lambs[-1]]
    if it > 1 and negativo:
        l_rs = [p.a[0],p.a[1],p.a[2], p.b[0], p.b[1], p.b[2],p.d[0],p.d[1],p.d[2],p.r,lambs[0],lambs[1],lambs[-1]]

#         l_rs = [p.a[0],p.a[1],p.a[2], p.b[0], p.b[1], p.b[2],p.low[0],p.low[1],p.low[2],p.d[0],p.d[1],p.d[2],p.up[0],p.up[1],p.up[2],p.r,lambs[0],lambs[1],lambs[-1]]

        lista.append(l_rs)

In [207]:
np.savetxt('instance_test.txt', lista, delimiter = ' ',newline='\n', fmt="%f")

In [208]:
c = ''
with open("instance_test.txt", "r") as fd:
    c = StringIO(fd.read())

In [209]:
d = c.read()
c = StringIO(d) 
d = np.loadtxt(c) 
# feature_names = ['a1','a2','3', 'b1',, 'low', 'up', 'd', 'r','inicital_lamb', 'target']
feature_names = ['a1','a2','a3', 'b1','b2','b3', 'd1','d2','d3', 'r','inicital_lamb','second_lambda', 'final_lamb']
# feature_names = ['a1','a2','a3', 'b1','b2','b3', 'low1','low2','low3', 'd1','d2','d3','up1','up2','up3', 'r','inicital_lamb','second_lambda', 'final_lamb']

In [210]:
knapsack = {"data":d, "feature_names": feature_names}
dataset = pd.DataFrame(knapsack['data'], columns = knapsack['feature_names'])

In [211]:
# Coletando x e y

X = dataset.iloc[:,:-3]
y = dataset['inicital_lamb'].values

In [212]:
X

,a1,a2,a3,b1,b2,b3,d1,d2,d3,r
0,25.0,25.0,16.0,19.682407,13.120124,18.102972,24.0,21.0,13.0,560.439338
1,20.0,24.0,15.0,14.454569,19.828871,12.901162,10.0,16.0,10.0,533.076992
2,15.0,21.0,12.0,19.030024,10.371458,15.622964,13.0,11.0,14.0,429.257870
3,24.0,20.0,22.0,18.342693,21.610108,21.371474,17.0,25.0,13.0,599.860461
4,15.0,16.0,12.0,12.214586,16.236696,14.403264,23.0,25.0,15.0,483.216648
...,...,...,...,...,...,...,...,...,...,...
5609,22.0,24.0,23.0,22.431542,18.913104,13.500982,21.0,10.0,19.0,532.079605
5610,10.0,17.0,12.0,21.630691,18.442863,12.108783,11.0,21.0,22.0,435.381647
5611,15.0,25.0,17.0,13.032678,12.862658,21.355984,23.0,19.0,20.0,466.830439
5612,18.0,19.0,10.0,23.744134,13.831530,18.394118,12.0,24.0,15.0,558.619303
5613,10.0,18.0,10.0,10.171612,15.226939,11.620342,19.0,14.0,20.0,281.806755

In [213]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [214]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [215]:
# Padronização
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [216]:
# Aplicando a padronização aos dados
X_train_p = scaler.transform(X_train)
X_test_p = scaler.transform(X_test)

In [217]:
# from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

In [218]:
# mlp = MLPClassifier(hidden_layer_sizes = (30,30,30))
regr = MLPRegressor(activation='logistic',random_state=1, max_iter=5000).fit(X_train_p, y_train)

In [219]:
regr.fit(X_train_p, y_train)

MLPRegressor(activation='logistic', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(100,), learning_rate='constant',
             learning_rate_init=0.001, max_fun=15000, max_iter=5000,
             momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
             power_t=0.5, random_state=1, shuffle=True, solver='adam',
             tol=0.0001, validation_fraction=0.1, verbose=False,
             warm_start=False)

In [220]:
regr.predict(X_test_p[:10])

array([ 8.90906934,  7.95807238,  5.89443153,  5.70278006,  5.74054624,
       10.73497476,  4.17704292,  7.53015243,  6.81120721,  7.35409258])

In [221]:
regr.score(X_test_p, y_test)

0.9966947040564246

In [222]:
y_test[:10]

array([ 9.009949,  8.047041,  5.938743,  5.786816,  5.723255, 10.74975 ,
        4.195061,  7.631199,  6.928953,  7.254569])

In [223]:
dataset

,a1,a2,a3,b1,b2,b3,d1,d2,d3,r,inicital_lamb,second_lambda,final_lamb
0,25.0,25.0,16.0,19.682407,13.120124,18.102972,24.0,21.0,13.0,560.439338,10.132414,11.209328,10.996768
1,20.0,24.0,15.0,14.454569,19.828871,12.901162,10.0,16.0,10.0,533.076992,7.326712,7.534589,7.534589
2,15.0,21.0,12.0,19.030024,10.371458,15.622964,13.0,11.0,14.0,429.257870,6.793340,7.018189,7.206010
3,24.0,20.0,22.0,18.342693,21.610108,21.371474,17.0,25.0,13.0,599.860461,7.071648,11.230246,9.291094
4,15.0,16.0,12.0,12.214586,16.236696,14.403264,23.0,25.0,15.0,483.216648,14.689023,14.979127,14.979127
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5609,22.0,24.0,23.0,22.431542,18.913104,13.500982,21.0,10.0,19.0,532.079605,6.445682,7.484068,7.484068
5610,10.0,17.0,12.0,21.630691,18.442863,12.108783,11.0,21.0,22.0,435.381647,6.027540,8.533032,9.764904
5611,15.0,25.0,17.0,13.032678,12.862658,21.355984,23.0,19.0,20.0,466.830439,10.881537,12.445408,13.842132
5612,18.0,19.0,10.0,23.744134,13.831530,18.394118,12.0,24.0,15.0,558.619303,6.448115,13.517327,13.458390
5613,10.0,18.0,10.0,10.171612,15.226939,11.620342,19.0,14.0,20.0,281.806755,8.730174,15.655231,13.865681